name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: github.repository_owner == 'expressive-code'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Check for unreleased changesets
        id: has-changesets
        uses: andstor/file-existence-action@v2
        with:
          files: ".changeset/!(README).md"
      
      # Run changesets action either if there are unreleased changesets (= a PR must be created)
      # or if the commit message starts with "Release" (= new versions must be published to NPM)
      - name: Create changesets PR or publish to NPM
        id: changesets
        if: steps.has-changesets.outputs.files_exists == 'true' || startsWith(github.event.head_commit.message, 'Release')
        uses: changesets/action@v1
        with:
          title: 'Release'
          version: 'pnpm changeset version && pnpm install --no-frozen-lockfile'
          publish: 'pnpm build && pnpm changeset publish'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
